/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class comparisonTests_NativeLib2 */

#ifndef _Included_comparisonTests_NativeLib2
#define _Included_comparisonTests_NativeLib2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     comparisonTests_NativeLib2
 * Method:    getData
 * Signature: (Ljava/lang/String;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_comparisonTests_NativeLib2_getData
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
