/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class comparisonTests_NativeLib */

#ifndef _Included_comparisonTests_NativeLib
#define _Included_comparisonTests_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     comparisonTests_NativeLib
 * Method:    getData
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_comparisonTests_NativeLib_getData
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
