/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dataObjectTests_NativeLib */

#ifndef _Included_dataObjectTests_NativeLib
#define _Included_dataObjectTests_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dataObjectTests_NativeLib
 * Method:    getData
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dataObjectTests_NativeLib_getData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
