/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dataTests_NativeLib1 */

#ifndef _Included_dataTests_NativeLib1
#define _Included_dataTests_NativeLib1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dataTests_NativeLib1
 * Method:    getData
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_dataTests_NativeLib1_getData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
