/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dataObjectTests_NativeLib1 */

#ifndef _Included_dataObjectTests_NativeLib1
#define _Included_dataObjectTests_NativeLib1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dataObjectTests_NativeLib1
 * Method:    getData
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_dataObjectTests_NativeLib1_getData
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
