/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dataObjectTests_NativeLib5 */

#ifndef _Included_dataObjectTests_NativeLib5
#define _Included_dataObjectTests_NativeLib5
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dataObjectTests_NativeLib5
 * Method:    getData
 * Signature: (Ljava/lang/String;)[S
 */
JNIEXPORT jshortArray JNICALL Java_dataObjectTests_NativeLib5_getData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dataObjectTests_NativeLib5
 * Method:    getData2
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_dataObjectTests_NativeLib5_getData2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
