/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dataObjectTests_NativeLib17 */

#ifndef _Included_dataObjectTests_NativeLib17
#define _Included_dataObjectTests_NativeLib17
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dataObjectTests_NativeLib17
 * Method:    getData
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_dataObjectTests_NativeLib17_getData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
