/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dataObjectTests_NativeLib15 */

#ifndef _Included_dataObjectTests_NativeLib15
#define _Included_dataObjectTests_NativeLib15
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dataObjectTests_NativeLib15
 * Method:    getData
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_dataObjectTests_NativeLib15_getData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
