/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dataObjectTests_NativeLib6 */

#ifndef _Included_dataObjectTests_NativeLib6
#define _Included_dataObjectTests_NativeLib6
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dataObjectTests_NativeLib6
 * Method:    getData
 * Signature: (Ljava/lang/String;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_dataObjectTests_NativeLib6_getData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dataObjectTests_NativeLib6
 * Method:    getData2
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_dataObjectTests_NativeLib6_getData2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
