/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dataObjectTests_NativeLib2 */

#ifndef _Included_dataObjectTests_NativeLib2
#define _Included_dataObjectTests_NativeLib2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dataObjectTests_NativeLib2
 * Method:    getData
 * Signature: ()[I
 */
JNIEXPORT jfloatArray JNICALL Java_dataObjectTests_NativeLib2_getData
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
