/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class comparisonTests_NativeLib3 */

#ifndef _Included_comparisonTests_NativeLib3
#define _Included_comparisonTests_NativeLib3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     comparisonTests_NativeLib3
 * Method:    getData
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_comparisonTests_NativeLib3_getData
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
