/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dataObjectTests_NativeLib3 */

#ifndef _Included_dataObjectTests_NativeLib3
#define _Included_dataObjectTests_NativeLib3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dataObjectTests_NativeLib3
 * Method:    getData
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_dataObjectTests_NativeLib3_getData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dataObjectTests_NativeLib3
 * Method:    getData2
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_dataObjectTests_NativeLib3_getData2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
