/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dataObjectTests_NativeLib10 */

#ifndef _Included_dataObjectTests_NativeLib10
#define _Included_dataObjectTests_NativeLib10
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dataObjectTests_NativeLib10
 * Method:    getData
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_dataObjectTests_NativeLib10_getData
  (JNIEnv *, jobject);

/*
 * Class:     dataObjectTests_NativeLib10
 * Method:    getData2
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_dataObjectTests_NativeLib10_getData2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
