/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dataObjectTests_NativeLib4 */

#ifndef _Included_dataObjectTests_NativeLib4
#define _Included_dataObjectTests_NativeLib4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dataObjectTests_NativeLib4
 * Method:    getData
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobject JNICALL Java_dataObjectTests_NativeLib4_getData
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
