/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class comparisonTests_NativeLib40 */

#ifndef _Included_comparisonTests_NativeLib40
#define _Included_comparisonTests_NativeLib40
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     comparisonTests_NativeLib40
 * Method:    getData
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_comparisonTests_NativeLib40_getData
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
